---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  apiServerAddress: "0.0.0.0"
  disableDefaultCNI: true

# add to the apiServer certSANs the name of the docker (dind) service in order to be able to reach the cluster through it
#kubeadmConfigPatchesJSON6902:
#  - group: kubeadm.k8s.io
#    version: v1beta2
#    kind: ClusterConfiguration
#    patch: |
#      - op: add
#        path: /apiServer/certSANs/-
#        value: 172.17.0.1

# patch the generated kubeadm config with some extra settings
#kubeadmConfigPatches:
#  - |
#    apiVersion: kubeadm.k8s.io/v1beta2
#    kind: ClusterConfiguration
#    metadata:
#      name: config
#    apiServer:
#      extraArgs:
#        enable-admission-plugins: NodeRestriction,PodSecurityPolicy

# image list
    # image: kindest/node:v1.20.2@sha256:15d3b5c4f521a84896ed1ead1b14e4774d02202d5c65ab68f30eeaf310a3b1a7
    # image: kindest/node:v1.21.2@sha256:9d07ff05e4afefbba983fac311807b3c17a5f36e7061f6cb7e2ba756255b2be4
    # image: kindest/node:v1.22.4@sha256:ca3587e6e545a96c07bf82e2c46503d9ef86fc704f44c17577fca7bcabf5f978
    # image: kindest/node:v1.23.1@sha256:355a1e3b7b0fe315c896f63a73847c554aac8fb8615c6bf47f1ca303009e9a2d

nodes:
  - role: control-plane
    image: kindest/node:v1.23.1@sha256:355a1e3b7b0fe315c896f63a73847c554aac8fb8615c6bf47f1ca303009e9a2d
#  - role: control-plane
#    image: kindest/node:v1.23.1@sha256:355a1e3b7b0fe315c896f63a73847c554aac8fb8615c6bf47f1ca303009e9a2d
#  - role: control-plane
#    image: kindest/node:v1.23.1@sha256:355a1e3b7b0fe315c896f63a73847c554aac8fb8615c6bf47f1ca303009e9a2d
#  - role: worker
#    image: kindest/node:v1.23.1@sha256:355a1e3b7b0fe315c896f63a73847c554aac8fb8615c6bf47f1ca303009e9a2d
